POST   http://127.0.0.1:8000/login
Content-Type: application/json

{"username":"zack", "password":"Pass1234"}

###

POST   http://127.0.0.1:8000/signup
Content-Type: application/json

{"username":"zack1", "password":"Pass1234", "email":"zack@sample.com"}

###

GET   http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 3064b30a1af6650389456222cb22b1e02db0a886